
USE [demographic_warehouse_advanced]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE CLUSTERED COLUMNSTORE INDEX [ccix_age_group] ON [dim].[age_group] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
CREATE CLUSTERED COLUMNSTORE INDEX [ccix_building_size] ON [dim].[building_size] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
CREATE CLUSTERED COLUMNSTORE INDEX [ccix_datasource_type] ON [dim].[datasource_type] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
CREATE CLUSTERED COLUMNSTORE INDEX [ccix_datasource] ON [dim].[datasource] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
CREATE CLUSTERED COLUMNSTORE INDEX [ccix_development_type] ON [dim].[development_type] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
CREATE CLUSTERED COLUMNSTORE INDEX [ccix_employment_type] ON [dim].[employment_type] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
CREATE CLUSTERED COLUMNSTORE INDEX [ccix_ethnicity] ON [dim].[ethnicity] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
CREATE CLUSTERED COLUMNSTORE INDEX [ccix_forecast_year] ON [dim].[forecast_year] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
CREATE CLUSTERED COLUMNSTORE INDEX [ccix_household_type] ON [dim].[household_type] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
CREATE CLUSTERED COLUMNSTORE INDEX [ccix_housing_type] ON [dim].[housing_type] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
CREATE CLUSTERED COLUMNSTORE INDEX [ccix_income_group] ON [dim].[income_group] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
CREATE CLUSTERED COLUMNSTORE INDEX [ccix_land_use_type] ON [dim].[land_use_type] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
CREATE CLUSTERED COLUMNSTORE INDEX [ccix_mgra] ON [dim].[mgra] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
CREATE CLUSTERED COLUMNSTORE INDEX [ccix_mgra_denormalize] ON [dim].[mgra_denormalize] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
CREATE CLUSTERED COLUMNSTORE INDEX [ccix_sex] ON [dim].[sex] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
CREATE CLUSTERED COLUMNSTORE INDEX [ccix_structure_type] ON [dim].[structure_type] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
CREATE CLUSTERED COLUMNSTORE INDEX [ccix_yr] ON [dim].[yr] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
GO

CREATE CLUSTERED COLUMNSTORE INDEX [ccix_age] ON [fact].[age] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
CREATE CLUSTERED COLUMNSTORE INDEX [ccix_age_sex_ethnicity] ON [fact].[age_sex_ethnicity] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
CREATE CLUSTERED COLUMNSTORE INDEX [ccix_ethnicity] ON [fact].[ethnicity] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
CREATE CLUSTERED COLUMNSTORE INDEX [ccix_household_income] ON [fact].[household_income] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
CREATE CLUSTERED COLUMNSTORE INDEX [ccix_housing] ON [fact].[housing] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
CREATE CLUSTERED COLUMNSTORE INDEX [ccix_jobs] ON [fact].[jobs] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
CREATE CLUSTERED COLUMNSTORE INDEX [ccix_land_use] ON [fact].[land_use] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
CREATE CLUSTERED COLUMNSTORE INDEX [ccix_population] ON [fact].[population] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
CREATE CLUSTERED COLUMNSTORE INDEX [ccix_price_index_sd] ON [fact].[price_index_sd] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
CREATE CLUSTERED COLUMNSTORE INDEX [ccix_sex] ON [fact].[sex] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
CREATE CLUSTERED COLUMNSTORE INDEX [ccix_syn_households] ON [fact].[syn_households] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
CREATE CLUSTERED COLUMNSTORE INDEX [ccix_syn_persons] ON [fact].[syn_persons] WITH (DROP_EXISTING = OFF, COMPRESSION_DELAY = 0) ON [PRIMARY];
GO